# Generated by Django 2.0.4 on 2018-06-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='content',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='todo',
            name='tesk_medium',
            field=models.CharField(choices=[('easy', 'Easy'), ('moderate', 'moderate'), ('complex', 'complex')], default=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.CharField(default='', max_length=128),
        ),
    ]
