# Generated by Django 2.0.4 on 2018-06-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20180608_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='content',
            field=models.TextField(default='', max_length=500),
        ),
    ]
