# Generated by Django 2.0.4 on 2018-06-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_auto_20180608_1835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='todo',
            name='content',
            field=models.TextField(default='', max_length=500),
        ),
    ]
