# Generated by Django 2.0.4 on 2018-06-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20180609_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='tesk_medium',
            field=models.CharField(choices=[('easy', 'Easy'), ('moderate', 'moderate'), ('complex', 'complex')], default=True, max_length=13),
        ),
    ]
