# Generated by Django 2.0.4 on 2018-06-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_todo_tesk_medium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='todolist',
        ),
        migrations.AddField(
            model_name='todo',
            name='mark_done',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='TodoList',
        ),
    ]
