# Generated by Django 2.0.4 on 2018-06-09 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0007_auto_20180609_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='answered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answerd', to=settings.AUTH_USER_MODEL),
        ),
    ]
